version: '3.8'

services:
  postgres:
    image: postgres
    container_name: contenedor_plan_de_carrera
    environment:
      POSTGRES_USER: aleira
      POSTGRES_PASSWORD: shifta20
      POSTGRES_DB: sql_dev
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aleira"]
      interval: 10s
      timeout: 5s
      retries: 5
